services:
  - type: web
    name: avto-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && flask db upgrade"
    startCommand: "gunicorn wsgi:app"
    envVars:
      - key: FLASK_ENV
        value: production
